// CaseBuddy AI — shared print-to-PDF export
// One styled print window for every export in the app (witness prep pioneered
// the pattern: styled HTML → Blob → window.open → print). Keep exports light —
// no jsPDF. Every artifact carries the not-legal-advice disclaimer.

import { getFirm } from './firmStore';

export function exportFooter(): string {
  const firm = getFirm();
  const brand = firm.whiteLabel && firm.firmName ? firm.firmName : 'CaseBuddy AI · casebuddy.live';
  return `<div class="footer">Generated by ${escapeHtml(brand)} · ${new Date().toLocaleDateString()} · This is a legal preparation tool, not legal advice.</div>`;
}

export function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const PRINT_STYLES = `
body{font-family:Georgia,serif;max-width:720px;margin:40px auto;padding:20px;color:#1a1a1a;line-height:1.6}
h1{font-size:22px;border-bottom:2px solid #1a1a1a;padding-bottom:8px}
h2{font-size:15px;color:#444;margin-top:26px;text-transform:uppercase;letter-spacing:1px}
.meta{color:#666;font-size:13px;margin-bottom:20px}
ol,ul{padding-left:20px}li{margin-bottom:6px}
table{width:100%;border-collapse:collapse;font-size:13px}
td,th{border:1px solid #ddd;padding:6px 8px;text-align:left;vertical-align:top}
th{background:#f5f5f5}
.danger{color:#c00}
.box{background:#fafafa;padding:14px 16px;border-left:3px solid #333;margin:14px 0}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #ddd;font-size:11px;color:#999;text-align:center}
@media print{body{margin:0}}
`;

// Opens the browser print dialog on a styled standalone document.
export function openPrintExport(title: string, bodyHtml: string) {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>${PRINT_STYLES}</style></head><body>${bodyHtml}${exportFooter()}</body></html>`;
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) setTimeout(() => { win.print(); }, 500);
}
