/**
 * Demo Case Data — Shumpert Federal Courthouse Arrest
 * Real case data for proof-of-concept demonstration
 */

import { Case, CaseStatus, EvidenceItem, DocumentType, CaseTask, Witness, TimelineEvent } from '../types';

const CASE_ID = 'demo-shumpert-2026';

const demoEvidence: EvidenceItem[] = [
  {
    id: 'ev-video-part1',
    caseId: CASE_ID,
    title: 'Arrest Video — Part 1 (Encounter & Confrontation)',
    type: DocumentType.EVIDENCE,
    source: 'file',
    summary: 'Video recording of initial encounter at Thomas G. Abernethy Federal Building parking lot. Shows Aberdeen Police Chief D. Shumpert approaching plaintiff, demanding identification, refusing courthouse access, and escalating to arrest threats. Captures officer stating "You have to go file it somewhere else" and "If you\'re not trying to go to jail, you need to put your phone down."',
    keyEntities: ['Chief D. Shumpert', 'Matthew Reardon', 'Thomas G. Abernethy Federal Building', 'Aberdeen Police'],
    risks: ['Chain of custody must be established', 'Audio quality varies in portions'],
    addedAt: '2026-06-04T14:30:00Z',
    fileName: 'arrest-video-part1.mp4',
    notes: 'Critical evidence — captures constitutional violations in real-time. Officer clearly denies access to federal courthouse.',
  },
  {
    id: 'ev-video-part2',
    caseId: CASE_ID,
    title: 'Arrest Video — Part 2 (Arrest & Vehicle Search)',
    type: DocumentType.EVIDENCE,
    source: 'file',
    summary: 'Continuation of encounter showing physical arrest, handcuffing, warrantless search of plaintiff\'s vehicle, phone seizure, and vehicle towing. Documents coordination between multiple officers. Captures plaintiff stating "I had a lawsuit to file. You know that." and officer replying "And all you had to do was identify yourself."',
    keyEntities: ['Chief D. Shumpert', 'Matthew Reardon', 'Aberdeen Police Officers'],
    risks: ['Defendant may argue exigent circumstances for vehicle search'],
    addedAt: '2026-06-04T14:45:00Z',
    fileName: 'arrest-video-part2.mp4',
    notes: 'Shows warrantless search — key Fourth Amendment evidence. Phone containing evidence of prior misconduct was seized.',
  },
  {
    id: 'ev-complaint-1983',
    caseId: CASE_ID,
    title: 'Federal §1983 Complaint (Filed)',
    type: DocumentType.MOTION,
    source: 'file',
    summary: '42 U.S.C. § 1983 civil rights complaint against Aberdeen Police Chief D. Shumpert and Union County officials. Alleges First Amendment retaliation, Fourth Amendment unreasonable seizure, and Fourteenth Amendment due process violations. Filed in the Northern District of Mississippi.',
    keyEntities: ['42 U.S.C. § 1983', 'Northern District of Mississippi', 'Chief D. Shumpert', 'Union County Sheriff'],
    risks: ['Qualified immunity defense likely', 'Must establish clearly established law'],
    addedAt: '2026-06-04T12:00:00Z',
    fileName: 'section-1983-complaint.pdf',
    notes: 'One of 6 federal court filings plaintiff was attempting to file when arrested.',
  },
  {
    id: 'ev-prior-arrest-1',
    caseId: CASE_ID,
    title: 'Prior Arrest Records — Union County (Arrest #1)',
    type: DocumentType.EVIDENCE,
    source: 'file',
    summary: 'Documentation of first arrest by Union County officials for exercising First Amendment rights. Establishes pattern of retaliation and retaliatory arrest. Includes booking records and charging documents.',
    keyEntities: ['Union County Sheriff', 'Matthew Reardon'],
    risks: [],
    addedAt: '2026-05-28T10:00:00Z',
    fileName: 'prior-arrest-1-records.pdf',
    notes: 'Establishes pattern — critical for showing retaliatory motive.',
  },
  {
    id: 'ev-prior-arrest-2',
    caseId: CASE_ID,
    title: 'Prior Arrest Records — Union County (Arrest #2)',
    type: DocumentType.EVIDENCE,
    source: 'file',
    summary: 'Documentation of second arrest by Union County officials. Further establishes pattern of retaliatory conduct. Plaintiff was engaged in constitutionally protected speech/press activity at time of arrest.',
    keyEntities: ['Union County Sheriff', 'Matthew Reardon'],
    risks: [],
    addedAt: '2026-06-01T10:00:00Z',
    fileName: 'prior-arrest-2-records.pdf',
    notes: 'Second arrest — phone seized containing evidence of officer misconduct (Fourth Amendment violation).',
  },
  {
    id: 'ev-transcript',
    caseId: CASE_ID,
    title: 'Verbatim Transcript — Courthouse Encounter',
    type: DocumentType.DEPOSITION,
    source: 'text',
    summary: 'Complete verbatim transcript of all dialogue between plaintiff Matthew Reardon and Aberdeen Police Chief D. Shumpert during the federal courthouse encounter on June 4, 2026. Key exchanges include: Officer demanding ID for courthouse access, plaintiff asserting right to file lawsuit, officer threatening arrest, and plaintiff\'s statement "I have a right to access the court. I am filing an emergency civil rights lawsuit."',
    keyEntities: ['Chief D. Shumpert', 'Matthew Reardon'],
    risks: [],
    addedAt: '2026-06-04T16:00:00Z',
    fileName: 'transcript-courthouse-encounter.pdf',
    notes: 'Officer\'s statement "You have to go file it somewhere else" is the most damning — directly denying court access.',
  },
  {
    id: 'ev-federal-filings',
    caseId: CASE_ID,
    title: 'All 6 Federal Court Filings Package',
    type: DocumentType.MOTION,
    source: 'file',
    summary: 'Complete package of all 6 federal court filings plaintiff was carrying and attempting to file at the time of arrest. Includes: §1983 complaint, emergency TRO application, motion for preliminary injunction, memorandum of law, affidavit of facts, and proposed order.',
    keyEntities: ['Northern District of Mississippi', 'Union County Sheriff'],
    risks: [],
    addedAt: '2026-06-04T11:00:00Z',
    fileName: 'federal-filings-complete.pdf',
    notes: 'Proves plaintiff had legitimate legal business at the courthouse — demolishes any claim he was there for improper purposes.',
  },
  {
    id: 'ev-bodycam-june1',
    caseId: CASE_ID,
    title: 'Prior Arrest Video — June 1 (Phone Seizure)',
    type: DocumentType.EVIDENCE,
    source: 'file',
    summary: 'Video from June 1, 2026 arrest showing warrantless seizure of plaintiff\'s cell phone. Phone contained evidence of officers\' own misconduct from earlier encounters. Seizure occurred without warrant or consent.',
    keyEntities: ['Union County Officers', 'Matthew Reardon'],
    risks: ['Need to establish phone contents were relevant evidence of misconduct'],
    addedAt: '2026-06-01T15:00:00Z',
    fileName: 'june1-arrest-phone-seizure.mp4',
    notes: 'Spoliation issue — phone containing evidence of misconduct was seized by the very officers it incriminated.',
  },
];

const demoTasks: CaseTask[] = [
  {
    id: 'task-1',
    caseId: CASE_ID,
    title: 'File §1983 Complaint in Northern District of Mississippi',
    status: 'done',
    priority: 'high',
    notes: 'Complaint drafted and ready. Initial filing attempted June 4 but prevented by arrest.',
  },
  {
    id: 'task-2',
    caseId: CASE_ID,
    title: 'File Emergency TRO to prevent further arrests',
    status: 'open',
    priority: 'high',
    dueDate: '2026-06-11',
    notes: 'Need to prevent defendants from further retaliatory arrests while lawsuit is pending.',
  },
  {
    id: 'task-3',
    caseId: CASE_ID,
    title: 'Serve all defendants',
    status: 'open',
    priority: 'high',
    dueDate: '2026-07-04',
    notes: 'Chief Shumpert, Union County Sheriff, City of Aberdeen, individual officers.',
  },
  {
    id: 'task-4',
    caseId: CASE_ID,
    title: 'File motion to preserve body camera footage',
    status: 'open',
    priority: 'high',
    dueDate: '2026-06-18',
    notes: 'Must preserve all body/dash cam footage from June 1, June 4, and prior encounters.',
  },
  {
    id: 'task-5',
    caseId: CASE_ID,
    title: 'FOIA request for dispatch records',
    status: 'open',
    priority: 'medium',
    dueDate: '2026-06-25',
    notes: 'Who called Aberdeen PD to the federal courthouse? Need dispatch records to prove coordination.',
  },
  {
    id: 'task-6',
    caseId: CASE_ID,
    title: 'Subpoena Federal Protective Service records',
    status: 'open',
    priority: 'medium',
    notes: 'Determine if federal marshals/FPS were involved in routing arrest to local police.',
  },
  {
    id: 'task-7',
    caseId: CASE_ID,
    title: 'Prepare opposition to qualified immunity defense',
    status: 'open',
    priority: 'high',
    notes: 'Right of court access is clearly established — must compile controlling precedent.',
  },
  {
    id: 'task-8',
    caseId: CASE_ID,
    title: 'Draft discovery requests — interrogatories and RFPs',
    status: 'open',
    priority: 'medium',
    dueDate: '2026-07-15',
    notes: 'Focus on communication records between federal building security, FPS, and Aberdeen PD.',
  },
];

const demoWitnesses: Witness[] = [
  {
    id: 'wit-1',
    name: 'Matthew Reardon',
    role: 'Plaintiff / Journalist — We The People News',
    personality: 'Cooperative',
    credibilityScore: 92,
    avatarUrl: '',
  },
  {
    id: 'wit-2',
    name: 'Chief D. Shumpert',
    role: 'Defendant — Aberdeen Police Chief, Arresting Officer',
    personality: 'Hostile',
    credibilityScore: 35,
    avatarUrl: '',
  },
  {
    id: 'wit-3',
    name: 'Federal Protective Service Officer',
    role: 'Witness — Federal Building Security',
    personality: 'Nervous',
    credibilityScore: 60,
    avatarUrl: '',
  },
  {
    id: 'wit-4',
    name: 'Union County Sheriff',
    role: 'Defendant — Prior Arrests, Pattern of Retaliation',
    personality: 'Hostile',
    credibilityScore: 30,
    avatarUrl: '',
  },
];

export const DEMO_SHUMPERT_CASE: Case = {
  id: CASE_ID,
  title: 'Reardon v. Shumpert et al. — Federal Courthouse Arrest',
  client: 'Matthew Reardon (Pro Se / Journalist)',
  status: CaseStatus.PRE_TRIAL,
  opposingCounsel: 'City of Aberdeen Attorney (TBD)',
  judge: 'TBD — Northern District of Mississippi',
  nextCourtDate: '2026-07-15',
  summary: `On June 4, 2026, journalist Matthew Reardon traveled to the Thomas G. Abernethy Federal Building in Aberdeen, Mississippi to file an emergency federal civil rights lawsuit (42 U.S.C. § 1983) against Union County officials who had already arrested him twice for exercising his First Amendment rights.

He never made it inside.

Aberdeen Police Chief D. Shumpert arrested Reardon in the federal courthouse parking lot. His vehicle was searched without a warrant. His car was towed. His phone — containing evidence of prior officer misconduct — was seized.

The evidence shows clear coordination between federal building security and local city police. Rather than allowing Reardon to access the federal court to file his lawsuit, someone inside the building called Aberdeen PD. A municipal police chief then arrested a citizen on federal property for attempting to exercise his constitutional right to petition the courts.

This case involves:
• First Amendment retaliation — arrested for attempting to file a lawsuit (right to petition)
• First Amendment press freedom — plaintiff is an investigative journalist
• Fourth Amendment — warrantless vehicle search and phone seizure
• Fourteenth Amendment — due process violations, prosecution under vague municipal ordinances
• Right of Court Access — fundamental constitutional right denied
• Pattern of retaliation — three arrests in one week for protected activity
• Federal-local coordination — municipal officers acting on federal property at federal officers' direction`,
  winProbability: 78,
  tags: ['civil-rights', '§1983', 'first-amendment', 'retaliation', 'press-freedom', 'court-access', 'fourth-amendment', 'qualified-immunity'],
  evidence: demoEvidence,
  tasks: demoTasks,
  witnesses: demoWitnesses,
  docketNumber: 'Pending Filing',
  courtLocation: 'U.S. District Court, Northern District of Mississippi, Aberdeen Division',
  jurisdiction: 'federal',
  clientType: 'plaintiff',
  opposingParty: 'Aberdeen Police Chief D. Shumpert; Union County Sheriff; City of Aberdeen; John Does 1-5 (Federal Officers)',
  legalTheory: '42 U.S.C. § 1983 — Deprivation of civil rights under color of law. Plaintiff seeks compensatory and punitive damages for First Amendment retaliation (arrest for attempting to file lawsuit and exercise press freedoms), Fourth Amendment violations (warrantless search/seizure of vehicle and phone), Fourteenth Amendment due process violations, and denial of the fundamental right of access to the courts.',
  keyIssues: [
    'Right of access to courts — clearly established constitutional right denied',
    'First Amendment retaliation — arrested for attempting to file a civil rights lawsuit',
    'Qualified immunity — must show rights were clearly established (they are)',
    'Federal-local coordination — who authorized city police to arrest at federal courthouse?',
    'Warrantless search — vehicle and phone seized without warrant or probable cause',
    'Pattern of retaliation — 3 arrests in one week for protected First Amendment activity',
    'Phone seizure — phone contained evidence of officers\' own misconduct (spoliation concerns)',
    'Municipal liability (Monell) — City of Aberdeen policy or custom of retaliation',
  ],
  timelineEvents: [
    {
      id: 'te-1',
      date: '2026-05-28',
      title: 'First Arrest — Union County',
      description: 'Matthew Reardon arrested by Union County Sheriff\'s deputies while exercising First Amendment rights. First instance of retaliatory arrest.',
      type: 'incident',
      importance: 'high',
      tags: ['arrest', 'retaliation', 'first-amendment'],
    },
    {
      id: 'te-2',
      date: '2026-06-01',
      title: 'Second Arrest — Phone Seized',
      description: 'Second arrest by Union County officials. Phone containing evidence of officer misconduct was seized without a warrant. Plaintiff\'s evidence against officers confiscated by the very officers it incriminated.',
      type: 'incident',
      importance: 'critical',
      tags: ['arrest', 'phone-seizure', 'fourth-amendment'],
    },
    {
      id: 'te-3',
      date: '2026-06-04',
      title: 'Federal Courthouse Arrest — Chief Shumpert',
      description: 'Plaintiff traveled to Thomas G. Abernethy Federal Building to file emergency §1983 lawsuit. Aberdeen Police Chief D. Shumpert arrested him in the parking lot. Vehicle searched without warrant. Car towed. Prevented from accessing federal court.',
      type: 'incident',
      importance: 'critical',
      tags: ['arrest', 'courthouse', 'shumpert', 'vehicle-search'],
    },
    {
      id: 'te-4',
      date: '2026-06-04',
      title: 'Vehicle Searched & Towed',
      description: 'After arrest, officers conducted warrantless search of plaintiff\'s vehicle in the federal courthouse parking lot. Vehicle was subsequently towed. All 6 federal court filings were inside.',
      type: 'evidence',
      importance: 'high',
      tags: ['fourth-amendment', 'warrantless-search'],
    },
    {
      id: 'te-5',
      date: '2026-06-04',
      title: '§1983 Complaint Filed (Alternative Method)',
      description: 'Despite arrest, plaintiff was able to file the §1983 complaint through alternative means. Complaint names Chief Shumpert, Union County Sheriff, and City of Aberdeen.',
      type: 'filing',
      importance: 'critical',
      tags: ['§1983', 'complaint', 'federal-court'],
    },
    {
      id: 'te-6',
      date: '2026-06-06',
      title: 'Investigation Published — WTPNEWS.ORG',
      description: 'Full investigative article published on We The People News including video evidence, transcripts, all 6 federal filings, and legal analysis. Email blast sent to 335 subscribers.',
      type: 'other',
      importance: 'high',
      tags: ['media', 'publication', 'investigation'],
    },
  ],
};
